# ansible localhost -m setup | grep ansible
# ansible localhost -m setup | grep mount
# by this ad-hoc command , u will get all the ansible variable value

---
 - hosts: localhost
   tasks:
   - debug: var=ansible_facts
#.......................................
---
 - hosts: localhost
   gather_facts: false   # by defalut gather fact is true// and it will give the gather fact
   tasks:
   - debug: var=ansible_facts
#..................................................
# ansible localhost -m setup | grep ansible
---
 - hosts: all
   tasks:
   - debug:  
      msg:
       - "The os distribution is: {{ansible_distribution}}"
       - "THe os name is: {{ansible_system}}"
       - "The os family is: {{ansible_os_family}}"
       - "THe mount points are :{{ansible_mounts}}"
# this will replacement of below playbook
 - name: Finding os distribution and os name 
   hosts: all
   gather_facts: false
   tasks:
   - name: FInding os distribution
     shell: "cat /etc/os-release  | awk -F =  'NR==1 {print $2 }' | awk '{print $1}' | tr '\"' ' '"
     register: os_dist
   - name: Finding os name
     shell: "uname"
     register: os_name
   - debug:
      msg:
       - "The os distribution name is: {{os_dist.stdout}}"
       - "THe os name: {{os_name.stdout}}"
#......................................
