# sudo yum install nano

---
 - name: this is to install on web
   hosts: localhost
   gather_facts: no
   tasks: 
   - name: install httpd
     yum: name=httpd state=present
     become: yes
   - name: install wget
     yum: name=wgt state=present
     become: yes
